### ISSUE TITLE
message saying "private account" for suspended account

### ISSUE THREAD

**Issue by x0rld** [FixTweet/FixTweet#202] opened 2023-03-19 19:19 UTC
I tried to share this tweet and it says private account but when I open on twitter it says "suspended"
https://fxtwitter.com/midnight_piracy/status/1637465214600740865
https://twitter.com/midnight_piracy/
![image](https://user-images.githubusercontent.com/45242856/226203552-1abda9ea-d08b-4bde-9f80-99baf2dff22c.png)

I don't know if it's a twitter api limitation or a bug

**Comment by dangeredwolf** [comment] 2023-03-20 04:37
Duplicate of #43

**Closed by dangeredwolf** 2023-03-20 04:37 UTC
